# Generated by Django 5.0.1 on 2024-03-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
