# Generated by Django 5.0.1 on 2024-03-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesmanager', '0003_note_user_tag_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
